In [1]:
import numpy as np
import pandas as pd

In [2]:
# Employees table
emp = pd.DataFrame({
    "EmpID": [1, 2, 3, 4],
    "Name": ["Dev", "Rahul", "Amit", "Sneha"],
    "DeptID": [101, 102, 101, 103]
})

# Departments table
dept = pd.DataFrame({
    "DeptID": [101, 102, 104],
    "DeptName": ["IT", "HR", "Finance"]
})

print(emp)
print(dept)

   EmpID   Name  DeptID
0      1    Dev     101
1      2  Rahul     102
2      3   Amit     101
3      4  Sneha     103
   DeptID DeptName
0     101       IT
1     102       HR
2     104  Finance

In [6]:
# A) Merge
# pd.merge(left, right, on="column", how="type")
print("\nINNER:")
print(pd.merge(emp, dept, on="DeptID", how="inner"))
print("\nOUTER:")
print(pd.merge(emp, dept, on="DeptID", how="outer"))
print("\nLEFT:")
print(pd.merge(emp, dept, on="DeptID", how="left"))
print("\nRIGHT:")
print(pd.merge(emp, dept, on="DeptID", how="right"))

INNER:
   EmpID   Name  DeptID DeptName
0      1    Dev     101       IT
1      2  Rahul     102       HR
2      3   Amit     101       IT

OUTER:
   EmpID   Name  DeptID DeptName
0    1.0    Dev     101       IT
1    3.0   Amit     101       IT
2    2.0  Rahul     102       HR
3    4.0  Sneha     103      NaN
4    NaN    NaN     104  Finance

LEFT:
   EmpID   Name  DeptID DeptName
0      1    Dev     101       IT
1      2  Rahul     102       HR
2      3   Amit     101       IT
3      4  Sneha     103      NaN

RIGHT:
   EmpID   Name  DeptID DeptName
0    1.0    Dev     101       IT
1    3.0   Amit     101       IT
2    2.0  Rahul     102       HR
3    NaN    NaN     104  Finance

In [7]:
# merge with different column name
pd.merge(
    emp,
    dept,
    left_on="DeptID",
    right_on="DeptID", # here you can use different one
    how="left"
)

   EmpID   Name  DeptID DeptName
0      1    Dev     101       IT
1      2  Rahul     102       HR
2      3   Amit     101       IT
3      4  Sneha     103      NaN

In [12]:
# B) Join
# Easier when index is the key 
# (Here we created key(DeptID) as index for both first)
emp_idx = emp.set_index("DeptID")
dept_idx = dept.set_index("DeptID")
emp_idx.join(dept_idx)

        EmpID   Name DeptName
DeptID
101         1    Dev       IT
102         2  Rahul       HR
101         3   Amit       IT
103         4  Sneha      NaN

In [16]:
# C) Concatenation
df1 = pd.DataFrame({
    "Name": ["Dev", "Rahul"],
    "Marks": [85, 90]
})

df2 = pd.DataFrame({
    "Name": ["Amit", "Sneha"],
    "Marks": [88, 92]
})

print(df1)
print()
print(df2)

    Name  Marks
0    Dev     85
1  Rahul     90

    Name  Marks
0   Amit     88
1  Sneha     92

In [18]:
# 1. row-wise concate
pd.concat([df1, df2])

    Name  Marks
0    Dev     85
1  Rahul     90
0   Amit     88
1  Sneha     92

In [19]:
# 2. column-wise concate
pd.concat([df1, df2], axis=1)

    Name  Marks   Name  Marks
0    Dev     85   Amit     88
1  Rahul     90  Sneha     92

In [20]:
# 3. Reset index
pd.concat([df1, df2], ignore_index=True)

    Name  Marks
0    Dev     85
1  Rahul     90
2   Amit     88
3  Sneha     92