In [12]:
import pandas as pd

In [13]:
data = {
    "Name": ["Dev", "Rahul", "Amit", "Sneha", "Kiran", "Rohit"],
    "Age": [23, 53, 32, 36, 42, 26],
    "Department": ["IT", "IT", "HR", "HR", "IT", "HR"],
    "City": ["Pune", "Mumbai", "Pune", "Delhi", "Pune", "Delhi"],
    "Salary": [50000, 60000, 45000, 48000, 52000, 47000]
}

df = pd.DataFrame(data)
print(df)

    Name  Age Department    City  Salary
0    Dev   23         IT    Pune   50000
1  Rahul   53         IT  Mumbai   60000
2   Amit   32         HR    Pune   45000
3  Sneha   36         HR   Delhi   48000
4  Kiran   42         IT    Pune   52000
5  Rohit   26         HR   Delhi   47000

--------------------------------------------- 

✅ A) What is Pivot Table?
> It summarizes data using:
- rows (index)
- columns
- values
- aggregation functions

In [14]:
# 1. Avg salary by department
pd.pivot_table(
    df,
    index="Department",
    values="Salary",
    aggfunc="mean"
)

                  Salary
Department
HR          46666.666667
IT          54000.000000

In [15]:
# 2. Avg salary by dept & city
pd.pivot_table(
    df,
    index="Department",
    columns="City",
    values="Salary",
    aggfunc="mean"
)

City          Delhi   Mumbai     Pune
Department
HR          47500.0      NaN  45000.0
IT              NaN  60000.0  51000.0

In [16]:
# 3. Multiple aggregation
pd.pivot_table(
    df,
    index="Department",
    values="Salary",
    aggfunc=["mean", "min", "max"]
)

                    mean    min    max
                  Salary Salary Salary
Department
HR          46666.666667  45000  48000
IT          54000.000000  50000  60000

In [17]:
# 4. Fill missing values in pivot table 
pd.pivot_table(
    df,
    index="Department",
    columns="City",
    values="Salary",
    aggfunc="mean",
    fill_value=0
)

City          Delhi   Mumbai     Pune
Department
HR          47500.0      0.0  45000.0
IT              0.0  60000.0  51000.0

In [20]:
# 5. pivot table using multiple values
pd.pivot_table(
    df,
    index="Department",
    values=["Salary", "Age"],
    aggfunc=["mean", "sum"]
)

                 mean                sum
                  Age        Salary  Age  Salary
Department
HR          31.333333  46666.666667   94  140000
IT          39.333333  54000.000000  118  162000

✅ B) What is Crosstab?
>It is used to count frequency of combinations.

In [25]:
# 1) Count employees by Department
pd.crosstab(df["Department"], df["City"])

City        Delhi  Mumbai  Pune
Department
HR              2       0     1
IT              0       1     2

In [26]:
# 2) Count with margins
pd.crosstab(df["Department"], df["City"], margins=True)

City        Delhi  Mumbai  Pune  All
Department
HR              2       0     1    3
IT              0       1     2    3
All             2       1     3    6

In [27]:
# 3) Normalize (percentage)
pd.crosstab(df["Department"], df["City"], normalize=True)

City           Delhi    Mumbai      Pune
Department
HR          0.333333  0.000000  0.166667
IT          0.000000  0.166667  0.333333