In [14]:
import pandas as pd

In [15]:
data = {
    "Name": ["Dev", "Rahul", "Amit", "Sneha"],
    "Marks": [85, 90, 35, 72],
    "City": ["Pune", "Mumbai", "Delhi", "Pune"]
}

df = pd.DataFrame(data)
print(df)

    Name  Marks    City
0    Dev     85    Pune
1  Rahul     90  Mumbai
2   Amit     35   Delhi
3  Sneha     72    Pune

In [16]:
# 1. map() 
# > map works on series only (not on Dataframes)

# Converting names of city (if names doesn't exist it puts NaN there)
df["City"] = df["City"].map({
    "Pune": "MH",
    "Mumbai": "MH",
    "Delhi": "DL"
})
print(df)

    Name  Marks City
0    Dev     85   MH
1  Rahul     90   MH
2   Amit     35   DL
3  Sneha     72   MH

In [19]:
df["Grade"] = df["Marks"].map(lambda x: "Pass" if x >= 40 else "Fail")
df

    Name  Marks City Grade
0    Dev     85   MH  Pass
1  Rahul     90   MH  Pass
2   Amit     35   DL  Fail
3  Sneha     72   MH  Pass

In [ ]:
# 2. apply()
# works on Series and DataFrames both

# a) on series
df["Result"] = df["Marks"].apply(lambda x: "Pass" if x >= 40 else "Fail")
df

    Name  Marks City Grade Result
0    Dev     85   MH  Pass   Pass
1  Rahul     90   MH  Pass   Pass
2   Amit     35   DL  Fail   Fail
3  Sneha     72   MH  Pass   Pass

In [26]:
# b) on rows (axis=0)
# when logic needs multiple columns. 
df["Scholarship"] = df.apply(
    lambda row: "Yes" if row["Marks"] > 80 and row["City"] == "MH" else "No",
    axis=1
)
print(df)

    Name  Marks City Grade Result Scholarship
0    Dev     85   MH  Pass   Pass         Yes
1  Rahul     90   MH  Pass   Pass         Yes
2   Amit     35   DL  Fail   Fail          No
3  Sneha     72   MH  Pass   Pass          No

In [28]:
# c) on columns (axis=1)
df.apply(max) # max of all cols

Name           Sneha
Marks             90
City              MH
Grade           Pass
Result          Pass
Scholarship      Yes
dtype: object

In [ ]:
# 3. applymap()
# works on entire DataFrame
# This example is for basic idea
df.applymap(lambda x: x * 2)
df

C:\Users\Devendra Rajhans\AppData\Local\Temp\ipykernel_9228\730171231.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x * 2)

    Name  Marks City Grade Result Scholarship
0    Dev     85   MH  Pass   Pass         Yes
1  Rahul     90   MH  Pass   Pass         Yes
2   Amit     35   DL  Fail   Fail          No
3  Sneha     72   MH  Pass   Pass          No