In [59]:
import pandas as pd

In [60]:
data = {
    "Name": ["Dev", "Rahul", "Amit", "Sneha", "Kiran"],
    "City": ["Pune", "Mumbai", "Pune", "Delhi", "Pune"],
    "Department": ["IT", "HR", "IT", "HR", "IT"],
    "Grade": ["A", "B", "A", "C", "B"]
}

df = pd.DataFrame(data)
print(df)

df.memory_usage(deep=True)

    Name    City Department Grade
0    Dev    Pune         IT     A
1  Rahul  Mumbai         HR     B
2   Amit    Pune         IT     A
3  Sneha   Delhi         HR     C
4  Kiran    Pune         IT     B

Index         132
Name          267
City          268
Department    255
Grade         250
dtype: int64

In [61]:
# 1. Changing to category
df["City"] = df["City"].astype("category")
df["Department"] = df["Department"].astype("category")

df.dtypes

Name            object
City          category
Department    category
Grade           object
dtype: object

- Why Use Categorical Data?

✅ Uses less memory
✅ Faster operations
✅ Better for repeated values

In [62]:
df.memory_usage(deep=True) #less memory than above

Index         132
Name          267
City          275
Department    215
Grade         250
dtype: int64

In [63]:
# value_counts
df['City'].value_counts()

City
Pune      3
Delhi     1
Mumbai    1
Name: count, dtype: int64

In [64]:
# 2. category properties : 
df["City"].cat.categories
# -- Key points
# Categories are stored once, not per row
# Order matters (especially if ordered=True)

Index(['Delhi', 'Mumbai', 'Pune'], dtype='object')

In [65]:
df["City"].cat.codes
# -- An integer array where each value is the index position of the category for that row.
# - Using the categories above:

# Category | Code
# ----------------
# Delhi	   |   0
# Mumbai   |   1
# Pune	   |   2

0    2
1    1
2    2
3    0
4    2
dtype: int8

In [66]:
# 3. Rename category
df["Grade"] = df["Grade"].astype("category")
df["Grade"] = df["Grade"].cat.rename_categories({
    "A": "Excellent",
    "B": "Good",
    "C": "Average"
})
df

    Name    City Department      Grade
0    Dev    Pune         IT  Excellent
1  Rahul  Mumbai         HR       Good
2   Amit    Pune         IT  Excellent
3  Sneha   Delhi         HR    Average
4  Kiran    Pune         IT       Good

In [67]:
# 4. Reorder category
df["Grade"] = df["Grade"].cat.reorder_categories(
    ["Excellent", "Good", "Average"],
    ordered=True
)
df.sort_values('Grade')

    Name    City Department      Grade
0    Dev    Pune         IT  Excellent
2   Amit    Pune         IT  Excellent
1  Rahul  Mumbai         HR       Good
4  Kiran    Pune         IT       Good
3  Sneha   Delhi         HR    Average

In [68]:
# 5. Adding & removing category
df["Grade"] = df["Grade"].cat.add_categories(["Poor"])
df['Grade'].cat.categories

Index(['Excellent', 'Good', 'Average', 'Poor'], dtype='object')

In [70]:
df['Grade'] = df['Grade'].cat.remove_unused_categories()
df['Grade'].cat.categories

Index(['Excellent', 'Good', 'Average'], dtype='object')