In [42]:
import pandas as pd

In [43]:
df = pd.read_csv("melb_data.csv")
df.shape

(13580, 21)

In [44]:
# 1. You can read only required columns
pd.read_csv("melb_data.csv", usecols=["Address", "Rooms", "Price"])

                Address  Rooms      Price
0          85 Turner St      2  1480000.0
1       25 Bloomburg St      2  1035000.0
2          5 Charles St      3  1465000.0
3      40 Federation La      3   850000.0
4           55a Park St      4  1600000.0
...                 ...    ...        ...
13575      12 Strada Cr      4  1245000.0
13576     77 Merrett Dr      3  1031000.0
13577       83 Power St      3  1170000.0
13578      96 Verdon St      4  2500000.0
13579        6 Agnes St      4  1285000.0

[13580 rows x 3 columns]

In [45]:
# 2. Read files in chunks
chunks = pd.read_csv("melb_data.csv", chunksize=5000)

for chunk in chunks:
    print(chunk.shape)

(5000, 21)
(5000, 21)
(3580, 21)

In [46]:
data = {
    "Name": ["Dev", "Rahul", "Amit", "Sneha"],
    "Age": [23, 12, 55, 32],
    "Marks": [85, 90, 35, 72],
    "City": ["Pune", "Mumbai", "Delhi", "Pune"]
}

df2 = pd.DataFrame(data)
print(df2)

    Name  Age  Marks    City
0    Dev   23     85    Pune
1  Rahul   12     90  Mumbai
2   Amit   55     35   Delhi
3  Sneha   32     72    Pune

In [47]:
# 3. avoid apply() when possible
# slow
df2["Result"] = df2["Marks"].apply(lambda x: "Pass" if x >= 40 else "Fail")
print(df2)
print()
# Fast (vectorized)
df2["Result"] = df2["Marks"] >= 40
print(df2)

    Name  Age  Marks    City Result
0    Dev   23     85    Pune   Pass
1  Rahul   12     90  Mumbai   Pass
2   Amit   55     35   Delhi   Fail
3  Sneha   32     72    Pune   Pass

    Name  Age  Marks    City  Result
0    Dev   23     85    Pune    True
1  Rahul   12     90  Mumbai    True
2   Amit   55     35   Delhi   False
3  Sneha   32     72    Pune    True

In [48]:
# 4. use vectorized operations
df2["Total"] = df2["Marks"] * 1.1
df2

    Name  Age  Marks    City  Result  Total
0    Dev   23     85    Pune    True   93.5
1  Rahul   12     90  Mumbai    True   99.0
2   Amit   55     35   Delhi   False   38.5
3  Sneha   32     72    Pune    True   79.2

In [49]:
# 5. filter early (reduce data size)
df2 = df2[df2['Marks'] > 50]
df2

    Name  Age  Marks    City  Result  Total
0    Dev   23     85    Pune    True   93.5
1  Rahul   12     90  Mumbai    True   99.0
3  Sneha   32     72    Pune    True   79.2

In [52]:
# 6. Use query() for Readibility
df2.query("Marks > 50 and Age >= 20")

    Name  Age  Marks  City  Result  Total
0    Dev   23     85  Pune    True   93.5
3  Sneha   32     72  Pune    True   79.2

In [55]:
# 7. Use sort and groupby efficiently
df2.sort_values("Marks")
df2.groupby("City")["Marks"].mean()

City
Mumbai    90.0
Pune      78.5
Name: Marks, dtype: float64