In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("melb_data.csv")

In [3]:
df["Date"]

0         3/12/2016
1         4/02/2016
2         4/03/2017
3         4/03/2017
4         4/06/2016
            ...
13575    26/08/2017
13576    26/08/2017
13577    26/08/2017
13578    26/08/2017
13579    26/08/2017
Name: Date, Length: 13580, dtype: object

In [5]:
df[["Date", "Address"]] # 2 brackets imp

             Date           Address
0       3/12/2016      85 Turner St
1       4/02/2016   25 Bloomburg St
2       4/03/2017      5 Charles St
3       4/03/2017  40 Federation La
4       4/06/2016       55a Park St
...           ...               ...
13575  26/08/2017      12 Strada Cr
13576  26/08/2017     77 Merrett Dr
13577  26/08/2017       83 Power St
13578  26/08/2017      96 Verdon St
13579  26/08/2017        6 Agnes St

[13580 rows x 2 columns]

In [9]:
df.iloc[3:6, 7:9] # row 3 to 5 , column 7 to 8

        Date  Distance
3  4/03/2017       2.5
4  4/06/2016       2.5
5  7/05/2016       2.5

In [ ]:
df.iloc[2] # df.iloc[rows, columns]  by position

Suburb                      Abbotsford
Address                   5 Charles St
Rooms                                3
Type                                 h
Price                        1465000.0
Method                              SP
SellerG                         Biggin
Date                         4/03/2017
Distance                           2.5
Postcode                        3067.0
Bedroom2                           3.0
Bathroom                           2.0
Car                                0.0
Landsize                         134.0
BuildingArea                     150.0
YearBuilt                       1900.0
CouncilArea                      Yarra
Lattitude                     -37.8093
Longtitude                    144.9944
Regionname       Northern Metropolitan
Propertycount                   4019.0
Name: 2, dtype: object

In [13]:
df.loc[:, "Address"] # df.loc[rows, columns] by labels

0            85 Turner St
1         25 Bloomburg St
2            5 Charles St
3        40 Federation La
4             55a Park St
               ...
13575        12 Strada Cr
13576       77 Merrett Dr
13577         83 Power St
13578        96 Verdon St
13579          6 Agnes St
Name: Address, Length: 13580, dtype: object

In [21]:
# Filtering
df[(df["Car"] > 4) & (df["Price"] > 100000)]

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
51,Airport West,3 Deidre Ct,3,h,895000.0,PI,Rendina,10/09/2016,13.5,3042.0,...,1.0,6.0,1063.0,133.0,1975.0,Moonee Valley,-37.72490,144.87280,Western Metropolitan,3464.0
61,Airport West,138 Victory Rd,3,h,1042000.0,S,Nelson,16/07/2016,13.5,3042.0,...,2.0,5.0,612.0,174.0,1950.0,Moonee Valley,-37.71730,144.87960,Western Metropolitan,3464.0
146,Altona,29 Rose St,4,h,1780000.0,SP,Greg,4/06/2016,13.8,3018.0,...,3.0,6.0,1057.0,220.0,1962.0,Hobsons Bay,-37.86810,144.81900,Western Metropolitan,5301.0
186,Altona North,45 Hearn St,5,h,1085000.0,S,FN,3/09/2016,11.1,3025.0,...,3.0,6.0,592.0,251.0,1965.0,Hobsons Bay,-37.83880,144.85670,Western Metropolitan,5132.0
318,Ascot Vale,125 Epsom Rd,4,h,1100000.0,VB,Nelson,15/10/2016,5.9,3032.0,...,2.0,5.0,559.0,195.0,1920.0,Moonee Valley,-37.77910,144.91360,Western Metropolitan,6567.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13413,Essendon,54 Cooper St,5,h,2335000.0,SP,Barry,26/08/2017,7.5,3040.0,...,2.0,6.0,1012.0,222.0,1915.0,NaN,-37.74967,144.89770,Western Metropolitan,9264.0
13479,Langwarrin,83 Pindara Bvd,4,h,965000.0,PI,O'Brien,26/08/2017,41.0,3910.0,...,2.0,6.0,869.0,264.0,2007.0,NaN,-38.14508,145.18787,Eastern Victoria,8743.0
13483,Maribyrnong,88 The Esplanade,3,h,3400000.0,SP,Jas,26/08/2017,4.3,3032.0,...,1.0,5.0,2027.0,187.0,1964.0,NaN,-37.76570,144.89109,Western Metropolitan,4918.0
13527,Reservoir,1 Don St,4,h,1112000.0,S,RW,26/08/2017,12.0,3073.0,...,2.0,10.0,1002.0,170.0,1985.0,NaN,-37.70671,145.03086,Northern Metropolitan,21650.0
13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0

In [23]:
df[~(df["Car"] == 4)] # this is not ~

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13574,Westmeadows,9 Black St,3,h,582000.0,S,Red,26/08/2017,16.5,3049.0,...,2.0,2.0,256.0,NaN,NaN,NaN,-37.67917,144.89390,Northern Metropolitan,2474.0
13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,2.0,2.0,652.0,NaN,1981.0,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,2.0,2.0,333.0,133.0,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0
13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0

In [25]:
# filter with only required columns
df[df["Car"] == 4][["Car", "Address"]]

       Car         Address
63     4.0  6 Kittyhawk St
120    4.0      6 Smith St
124    4.0    83 Fulham Rd
145    4.0    20 Linnet St
152    4.0    173 Queen St
...    ...             ...
13486  4.0  17 Canadian Ct
13519  4.0        1 Ann St
13531  4.0   170 Coppin St
13535  4.0  30 Phillips Cr
13577  4.0     83 Power St

[506 rows x 2 columns]