In [73]:
import pandas as pd
import numpy as np

In [ ]:
# Missing values 
# Nan or None

In [75]:
data = {
    "Name": ["Dev", "Rahul", "Amit", None, "Sneha"],
    "Age": [20, np.nan, 22, 21, np.nan],
    "City": ["Pune", "Mumbai", None, "Delhi", "Pune"],
    "Marks": [85, 90, np.nan, 92, 88]
}

df = pd.DataFrame(data)
print(df)

    Name   Age    City  Marks
0    Dev  20.0    Pune   85.0
1  Rahul   NaN  Mumbai   90.0
2   Amit  22.0    None    NaN
3   None  21.0   Delhi   92.0
4  Sneha   NaN    Pune   88.0

In [76]:
# 1. finding null values
df.isnull() # true if null

    Name    Age   City  Marks
0  False  False  False  False
1  False   True  False  False
2  False  False   True   True
3   True  False  False  False
4  False   True  False  False

In [77]:
df.isnull().sum()

Name     1
Age      2
City     1
Marks    1
dtype: int64

In [78]:
df.notnull() # true if not null

    Name    Age   City  Marks
0   True   True   True   True
1   True  False   True   True
2   True   True  False  False
3  False   True   True   True
4   True  False   True   True

In [79]:
df.notnull().sum()

Name     4
Age      3
City     4
Marks    4
dtype: int64

In [80]:
# 2. droping null values
df1 = df.dropna() # drops rows with null values
print(df1)

  Name   Age  City  Marks
0  Dev  20.0  Pune   85.0

In [81]:
df2 = df.dropna(axis=1) # drops column with null values
print(df2)
# Empty as all columns have null values

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [82]:
df3 = df.dropna(how="all")
print(df3)
#drops only if all are null

    Name   Age    City  Marks
0    Dev  20.0    Pune   85.0
1  Rahul   NaN  Mumbai   90.0
2   Amit  22.0    None    NaN
3   None  21.0   Delhi   92.0
4  Sneha   NaN    Pune   88.0

In [83]:
df4 = df.dropna(subset=["Age"])
print(df4)
# drops only if age is null

   Name   Age   City  Marks
0   Dev  20.0   Pune   85.0
2  Amit  22.0   None    NaN
3  None  21.0  Delhi   92.0

In [84]:
# 3. Filling null values
df1 = df.fillna(0)
print(df1)

    Name   Age    City  Marks
0    Dev  20.0    Pune   85.0
1  Rahul   0.0  Mumbai   90.0
2   Amit  22.0       0    0.0
3      0  21.0   Delhi   92.0
4  Sneha   0.0    Pune   88.0

In [85]:
df1 = df
df1['Age'] = df['Age'].fillna(21)
print(df1)

    Name   Age    City  Marks
0    Dev  20.0    Pune   85.0
1  Rahul  21.0  Mumbai   90.0
2   Amit  22.0    None    NaN
3   None  21.0   Delhi   92.0
4  Sneha  21.0    Pune   88.0

In [86]:
df1['Marks'] = df1['Marks'].fillna(df1['Marks'].mean())
print(df1)

    Name   Age    City  Marks
0    Dev  20.0    Pune  85.00
1  Rahul  21.0  Mumbai  90.00
2   Amit  22.0    None  88.75
3   None  21.0   Delhi  92.00
4  Sneha  21.0    Pune  88.00

In [87]:
df1['City'] = df1['City'].fillna(df1['City'].mode()[0]) # df.mode() gives series. So, we need to take 0th index.
print(df1)

    Name   Age    City  Marks
0    Dev  20.0    Pune  85.00
1  Rahul  21.0  Mumbai  90.00
2   Amit  22.0    Pune  88.75
3   None  21.0   Delhi  92.00
4  Sneha  21.0    Pune  88.00

In [88]:
# 4. Replace
# If some values are not exact null values, then we need to change it to NaN format
# values can be (Na, -1, missing, etc.)
# for this we use replace
df.replace(-1, np.nan, inplace=True) 
df2 = df.replace('na', np.nan, inplace=False)
# inplace=True → changes df directly (no reassignment needed)
# inplace=False → returns a new modified copy

In [94]:
# 5. forward fill & backward fill
data = {
    "Name": ["Dev", "Rahul", "Amit", None, "Sneha"],
    "Age": [20, np.nan, 22, 21, np.nan],
    "City": ["Pune", "Mumbai", None, "Delhi", "Pune"],
    "Marks": [85, 90, np.nan, 92, 88]
}

df = pd.DataFrame(data)
print(df)
print("\nForward fill: \n", df.ffill())  # fills NaN with previous value
print("\nBackward fill: \n", df.bfill()) # fills NaN with next value

    Name   Age    City  Marks
0    Dev  20.0    Pune   85.0
1  Rahul   NaN  Mumbai   90.0
2   Amit  22.0    None    NaN
3   None  21.0   Delhi   92.0
4  Sneha   NaN    Pune   88.0

Forward fill:
     Name   Age    City  Marks
0    Dev  20.0    Pune   85.0
1  Rahul  20.0  Mumbai   90.0
2   Amit  22.0  Mumbai   90.0
3   Amit  21.0   Delhi   92.0
4  Sneha  21.0    Pune   88.0

Backward fill:
     Name   Age    City  Marks
0    Dev  20.0    Pune   85.0
1  Rahul  22.0  Mumbai   90.0
2   Amit  22.0   Delhi   92.0
3  Sneha  21.0   Delhi   92.0
4  Sneha   NaN    Pune   88.0

In [98]:
# 6. interpolate
# filling NaN with estimating them with nearby values
data = {
    "col1":[1, 2, 3],
    "col2":[10, None, 30]
}
df = pd.DataFrame(data)
print(df)
df['col2'] = df['col2'].interpolate()
print("\nAfter Interpolation:")
print(df)
# It estimated value 20 by analysing a seq

   col1  col2
0     1  10.0
1     2   NaN
2     3  30.0

After Interpolation:
   col1  col2
0     1  10.0
1     2  20.0
2     3  30.0