In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    "Name": ["Dev", "Rahul", "Amit", "Sneha", "Kiran"],
    "Age": [20, 21, 22, 19, 21],
    "City": ["Pune", "Mumbai", "Nashik", "Delhi", "Pune"],
    "Marks": [85, 90, 88, 92, 70]
}

df = pd.DataFrame(data)
print(df)

    Name  Age    City  Marks
0    Dev   20    Pune     85
1  Rahul   21  Mumbai     90
2   Amit   22  Nashik     88
3  Sneha   19   Delhi     92
4  Kiran   21    Pune     70

In [ ]:
# 1. sort_values (sort by column values)
df.sort_values("Marks") #default ascending

    Name  Age    City  Marks
4  Kiran   21    Pune     70
0    Dev   20    Pune     85
2   Amit   22  Nashik     88
1  Rahul   21  Mumbai     90
3  Sneha   19   Delhi     92

In [6]:
df.sort_values("Name", ascending=False) #descending (Z -> A)

    Name  Age    City  Marks
3  Sneha   19   Delhi     92
1  Rahul   21  Mumbai     90
4  Kiran   21    Pune     70
0    Dev   20    Pune     85
2   Amit   22  Nashik     88

In [ ]:
# 2. multiple columns 
df.sort_values(["City", "Marks"], ascending=[True, False]) 
# first sort 'City' then 'Marks' 
# ('City' -> ascending)  then ('Marks' -> descending)

    Name  Age    City  Marks
3  Sneha   19   Delhi     92
1  Rahul   21  Mumbai     90
2   Amit   22  Nashik     88
0    Dev   20    Pune     85
4  Kiran   21    Pune     70

In [ ]:
# 3. sort_index
df.sort_index() # ascending

    Name  Age    City  Marks
0    Dev   20    Pune     85
1  Rahul   21  Mumbai     90
2   Amit   22  Nashik     88
3  Sneha   19   Delhi     92
4  Kiran   21    Pune     70

In [11]:
df.sort_index(ascending=False) # descending

    Name  Age    City  Marks
4  Kiran   21    Pune     70
3  Sneha   19   Delhi     92
2   Amit   22  Nashik     88
1  Rahul   21  Mumbai     90
0    Dev   20    Pune     85

In [13]:
df.sort_index(inplace=True) # sorting & saving

In [15]:
# 4. sorting with missing values
df.sort_values("Name", na_position="first") # if NaN exist, then arranged  at first

    Name  Age    City  Marks
2   Amit   22  Nashik     88
0    Dev   20    Pune     85
4  Kiran   21    Pune     70
1  Rahul   21  Mumbai     90
3  Sneha   19   Delhi     92