In [1]:
import pandas as pd

In [2]:
data = {
    "Name": ["Dev", "Rahul", "Amit", "Sneha"],
    "Age": [20, 21, 22, 19],
    "Marks": [85, 90, 88, 92]
}

df = pd.DataFrame(data)
print(df)

    Name  Age  Marks
0    Dev   20     85
1  Rahul   21     90
2   Amit   22     88
3  Sneha   19     92

In [3]:
# A) Adding column
# 1. adding constant column
df['Country'] = "India"
print(df)

    Name  Age  Marks Country
0    Dev   20     85   India
1  Rahul   21     90   India
2   Amit   22     88   India
3  Sneha   19     92   India

In [4]:
# 2. add with calculation
df['Marks_Bonus'] = df['Marks']+5
print(df)

    Name  Age  Marks Country  Marks_Bonus
0    Dev   20     85   India           90
1  Rahul   21     90   India           95
2   Amit   22     88   India           93
3  Sneha   19     92   India           97

In [5]:
# 3. using condition { .apply() }
df['Result'] = df['Marks'].apply(lambda x: "Pass" if (x>=40) else "Fail")
df

    Name  Age  Marks Country  Marks_Bonus Result
0    Dev   20     85   India           90   Pass
1  Rahul   21     90   India           95   Pass
2   Amit   22     88   India           93   Pass
3  Sneha   19     92   India           97   Pass

In [6]:
# 4. using multiple columns 
df["Message"] = df['Name'] + " scored " + df["Marks"].astype(str) + " Marks."
df

    Name  Age  Marks Country  Marks_Bonus Result                 Message
0    Dev   20     85   India           90   Pass    Dev scored 85 Marks.
1  Rahul   21     90   India           95   Pass  Rahul scored 90 Marks.
2   Amit   22     88   India           93   Pass   Amit scored 88 Marks.
3  Sneha   19     92   India           97   Pass  Sneha scored 92 Marks.

In [7]:
# B) Updating column
df['Marks'] = df['Marks']-5
df

    Name  Age  Marks Country  Marks_Bonus Result                 Message
0    Dev   20     80   India           90   Pass    Dev scored 85 Marks.
1  Rahul   21     85   India           95   Pass  Rahul scored 90 Marks.
2   Amit   22     83   India           93   Pass   Amit scored 88 Marks.
3  Sneha   19     87   India           97   Pass  Sneha scored 92 Marks.

In [8]:
# C) Removing columns { .drop() }
# 1. remove one col
df.drop("Country", axis=1)

    Name  Age  Marks  Marks_Bonus Result                 Message
0    Dev   20     80           90   Pass    Dev scored 85 Marks.
1  Rahul   21     85           95   Pass  Rahul scored 90 Marks.
2   Amit   22     83           93   Pass   Amit scored 88 Marks.
3  Sneha   19     87           97   Pass  Sneha scored 92 Marks.

In [9]:
# 2. remove multiple cols
df.drop(["Country", "Marks_Bonus"], axis=1)

    Name  Age  Marks Result                 Message
0    Dev   20     80   Pass    Dev scored 85 Marks.
1  Rahul   21     85   Pass  Rahul scored 90 Marks.
2   Amit   22     83   Pass   Amit scored 88 Marks.
3  Sneha   19     87   Pass  Sneha scored 92 Marks.

In [10]:
# 3. remove Permanently 
df.drop("Country", axis=1, inplace=True)
df

    Name  Age  Marks  Marks_Bonus Result                 Message
0    Dev   20     80           90   Pass    Dev scored 85 Marks.
1  Rahul   21     85           95   Pass  Rahul scored 90 Marks.
2   Amit   22     83           93   Pass   Amit scored 88 Marks.
3  Sneha   19     87           97   Pass  Sneha scored 92 Marks.

In [11]:
# D) Inserting column
# df.insert(position, "col_name", values)
values = ["Pune", "Mumbai", "Nashik", "Pune"]
df.insert(2, "City", values)
df

    Name  Age    City  Marks  Marks_Bonus Result                 Message
0    Dev   20    Pune     80           90   Pass    Dev scored 85 Marks.
1  Rahul   21  Mumbai     85           95   Pass  Rahul scored 90 Marks.
2   Amit   22  Nashik     83           93   Pass   Amit scored 88 Marks.
3  Sneha   19    Pune     87           97   Pass  Sneha scored 92 Marks.

In [12]:
# E) Renaming 
df.rename(columns={ "Marks":"Score" }, inplace=True)
df

    Name  Age    City  Score  Marks_Bonus Result                 Message
0    Dev   20    Pune     80           90   Pass    Dev scored 85 Marks.
1  Rahul   21  Mumbai     85           95   Pass  Rahul scored 90 Marks.
2   Amit   22  Nashik     83           93   Pass   Amit scored 88 Marks.
3  Sneha   19    Pune     87           97   Pass  Sneha scored 92 Marks.