In [22]:
import numpy as np
import pandas as pd

In [23]:
data = {
    "Name": ["Dev", "Rahul", "Amit", "Sneha", "Kiran", "Rohit"],
    "Age": [21, 23, 43, 28, 25, 32],
    "Department": ["IT", "IT", "HR", "HR", "IT", "HR"],
    "City": ["Pune", "Mumbai", "Pune", "Delhi", "Pune", "Delhi"],
    "Salary": [50000, 60000, 45000, 48000, 52000, 47000]
}

df = pd.DataFrame(data)
print(df)

    Name  Age Department    City  Salary
0    Dev   21         IT    Pune   50000
1  Rahul   23         IT  Mumbai   60000
2   Amit   43         HR    Pune   45000
3  Sneha   28         HR   Delhi   48000
4  Kiran   25         IT    Pune   52000
5  Rohit   32         HR   Delhi   47000

In [24]:
# 1. Basic single aggregation
df.groupby("Department")["Salary"].mean()

Department
HR    46666.666667
IT    54000.000000
Name: Salary, dtype: float64

In [25]:
df.groupby("Department")["Salary"].sum()

Department
HR    140000
IT    162000
Name: Salary, dtype: int64

In [26]:
df.groupby("Department")["Name"].count()

Department
HR    3
IT    3
Name: Name, dtype: int64

In [27]:
# 2. Multiple Aggregation ( .agg() )
df.groupby("Department")["Salary"].agg(["min", "max", "std", "mean", "sum"])

              min    max          std          mean     sum
Department
HR          45000  48000  1527.525232  46666.666667  140000
IT          50000  60000  5291.502622  54000.000000  162000

In [28]:
# Renaming aggregation cols
df.groupby("Department").agg(
    min_salary = ("Salary", "min"),
    max_salary = ("Salary", "max"),
    mean_salary = ("Salary", "max"),
    sum_of_salary = ("Salary", "max")
)

            min_salary  max_salary  mean_salary  sum_of_salary
Department
HR               45000       48000        48000          48000
IT               50000       60000        60000          60000

In [29]:
# 3. Grp on multiple column
df.groupby(["Department", "City"])["Salary"].mean() # first Dept --> then City

Department  City
HR          Delhi     47500.0
            Pune      45000.0
IT          Mumbai    60000.0
            Pune      51000.0
Name: Salary, dtype: float64

In [33]:
# 4. Multiple columns selected
df.groupby("Department")[["Salary","Age"]].agg(["mean", "max"])

                  Salary               Age
                    mean    max       mean max
Department
HR          46666.666667  48000  34.333333  43
IT          54000.000000  60000  23.000000  25

In [39]:
# 5. with filtering 
df.groupby("Department")["Age"].mean().loc[lambda x: x>25]

Department
HR    34.333333
Name: Age, dtype: float64

In [40]:
# 6. with sorting
df.groupby("Department")["Age"].mean().sort_values(ascending=True)

Department
IT    23.000000
HR    34.333333
Name: Age, dtype: float64